services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    restart: always

  backend:
    build:
      context: ./backend
    container_name: nestjs-backend
    ports:
      - "3001:3001"
    environment:
      - PYTHON_API=http://model:5000
    depends_on:
      - model
    restart: always

  model:
    build:
      context: ./model
      dockerfile: Dockerfile
    ports:
      - "5000:5000"

  runs:
    image: python:3.12
    container_name: runs
    volumes:
      - ./runs:/models
    restart: always
