version: "3.8"

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    restart: always

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    restart: always
    depends_on:
      - model
      - runs
    environment:
      - MODEL_DIR=/app/runs

  model:
    build:
      context: ./model
      dockerfile: Dockerfile
    restart: always
    volumes:
      - ./runs:/app/runs

  runs:
    image: python:3.12
    container_name: runs
    volumes:
      - ./runs:/models
    restart: always
